<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLZmvGjx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLZmvGjx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLZmvGjx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLZmvGjx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLZmvGjx\App_KernelDevDebugContainer([
    'container.build_hash' => 'LZmvGjx',
    'container.build_id' => '265bd1b7',
    'container.build_time' => 1659264902,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLZmvGjx');
